[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Board configuration for ESP32-S3-FH4R2 (4MB Flash, 2MB PSRAM)
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1           ; Optimize for size
    -DCORE_DEBUG_LEVEL=0    ; Disable debug output
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=0
    -DCONFIG_ARDUINO_ISR_IRAM=0
	-DBOARD_HAS_PSRAM
    -DAUDIO_LOG
    -D LITTLEFS
    -D AUDIO_USE_PSRAM

; Partition scheme with OTA support
board_build.partitions = default.csv

; Upload settings
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    FastLED/FastLED
    file://C:\Users\moeburn\Documents\Arduino\libraries\Average-master
    wollewald/ADS1115_WE
    file://C:\Users\moeburn\Documents\Arduino\libraries\Blynk
    ArduinoOTA